/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as QuizBankRouteImport } from './routes/quiz-bank'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentQuizzesRouteImport } from './routes/student.quizzes'
import { Route as StudentLeaderboardRouteImport } from './routes/student.leaderboard'
import { Route as StudentCoursesRouteImport } from './routes/student.courses'
import { Route as StudentAchievementsRouteImport } from './routes/student.achievements'
import { Route as ParentScheduleRouteImport } from './routes/parent.schedule'
import { Route as ParentMessagesRouteImport } from './routes/parent.messages'
import { Route as ParentChildrenRouteImport } from './routes/parent.children'
import { Route as ParentBillingRouteImport } from './routes/parent.billing'
import { Route as AssistantReportsRouteImport } from './routes/assistant.reports'
import { Route as AssistantGradingRouteImport } from './routes/assistant.grading'
import { Route as AssistantDiscussionsRouteImport } from './routes/assistant.discussions'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizBankRoute = QuizBankRouteImport.update({
  id: '/quiz-bank',
  path: '/quiz-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentQuizzesRoute = StudentQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLeaderboardRoute = StudentLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAchievementsRoute = StudentAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => StudentRoute,
} as any)
const ParentScheduleRoute = ParentScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => ParentRoute,
} as any)
const ParentMessagesRoute = ParentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ParentRoute,
} as any)
const ParentChildrenRoute = ParentChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => ParentRoute,
} as any)
const ParentBillingRoute = ParentBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ParentRoute,
} as any)
const AssistantReportsRoute = AssistantReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AssistantRoute,
} as any)
const AssistantGradingRoute = AssistantGradingRouteImport.update({
  id: '/grading',
  path: '/grading',
  getParentRoute: () => AssistantRoute,
} as any)
const AssistantDiscussionsRoute = AssistantDiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => AssistantRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRouteWithChildren
  '/classes': typeof ClassesRoute
  '/marketplace': typeof MarketplaceRoute
  '/onboarding': typeof OnboardingRoute
  '/owner': typeof OwnerRoute
  '/parent': typeof ParentRouteWithChildren
  '/quiz-bank': typeof QuizBankRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/billing': typeof AdminBillingRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/assistant/discussions': typeof AssistantDiscussionsRoute
  '/assistant/grading': typeof AssistantGradingRoute
  '/assistant/reports': typeof AssistantReportsRoute
  '/parent/billing': typeof ParentBillingRoute
  '/parent/children': typeof ParentChildrenRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/parent/schedule': typeof ParentScheduleRoute
  '/student/achievements': typeof StudentAchievementsRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/quizzes': typeof StudentQuizzesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRouteWithChildren
  '/classes': typeof ClassesRoute
  '/marketplace': typeof MarketplaceRoute
  '/onboarding': typeof OnboardingRoute
  '/owner': typeof OwnerRoute
  '/parent': typeof ParentRouteWithChildren
  '/quiz-bank': typeof QuizBankRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/billing': typeof AdminBillingRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/assistant/discussions': typeof AssistantDiscussionsRoute
  '/assistant/grading': typeof AssistantGradingRoute
  '/assistant/reports': typeof AssistantReportsRoute
  '/parent/billing': typeof ParentBillingRoute
  '/parent/children': typeof ParentChildrenRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/parent/schedule': typeof ParentScheduleRoute
  '/student/achievements': typeof StudentAchievementsRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/quizzes': typeof StudentQuizzesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRouteWithChildren
  '/classes': typeof ClassesRoute
  '/marketplace': typeof MarketplaceRoute
  '/onboarding': typeof OnboardingRoute
  '/owner': typeof OwnerRoute
  '/parent': typeof ParentRouteWithChildren
  '/quiz-bank': typeof QuizBankRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/billing': typeof AdminBillingRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/assistant/discussions': typeof AssistantDiscussionsRoute
  '/assistant/grading': typeof AssistantGradingRoute
  '/assistant/reports': typeof AssistantReportsRoute
  '/parent/billing': typeof ParentBillingRoute
  '/parent/children': typeof ParentChildrenRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/parent/schedule': typeof ParentScheduleRoute
  '/student/achievements': typeof StudentAchievementsRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/quizzes': typeof StudentQuizzesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assistant'
    | '/classes'
    | '/marketplace'
    | '/onboarding'
    | '/owner'
    | '/parent'
    | '/quiz-bank'
    | '/student'
    | '/admin/billing'
    | '/admin/integrations'
    | '/admin/staff'
    | '/assistant/discussions'
    | '/assistant/grading'
    | '/assistant/reports'
    | '/parent/billing'
    | '/parent/children'
    | '/parent/messages'
    | '/parent/schedule'
    | '/student/achievements'
    | '/student/courses'
    | '/student/leaderboard'
    | '/student/quizzes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assistant'
    | '/classes'
    | '/marketplace'
    | '/onboarding'
    | '/owner'
    | '/parent'
    | '/quiz-bank'
    | '/student'
    | '/admin/billing'
    | '/admin/integrations'
    | '/admin/staff'
    | '/assistant/discussions'
    | '/assistant/grading'
    | '/assistant/reports'
    | '/parent/billing'
    | '/parent/children'
    | '/parent/messages'
    | '/parent/schedule'
    | '/student/achievements'
    | '/student/courses'
    | '/student/leaderboard'
    | '/student/quizzes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assistant'
    | '/classes'
    | '/marketplace'
    | '/onboarding'
    | '/owner'
    | '/parent'
    | '/quiz-bank'
    | '/student'
    | '/admin/billing'
    | '/admin/integrations'
    | '/admin/staff'
    | '/assistant/discussions'
    | '/assistant/grading'
    | '/assistant/reports'
    | '/parent/billing'
    | '/parent/children'
    | '/parent/messages'
    | '/parent/schedule'
    | '/student/achievements'
    | '/student/courses'
    | '/student/leaderboard'
    | '/student/quizzes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssistantRoute: typeof AssistantRouteWithChildren
  ClassesRoute: typeof ClassesRoute
  MarketplaceRoute: typeof MarketplaceRoute
  OnboardingRoute: typeof OnboardingRoute
  OwnerRoute: typeof OwnerRoute
  ParentRoute: typeof ParentRouteWithChildren
  QuizBankRoute: typeof QuizBankRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-bank': {
      id: '/quiz-bank'
      path: '/quiz-bank'
      fullPath: '/quiz-bank'
      preLoaderRoute: typeof QuizBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/quizzes': {
      id: '/student/quizzes'
      path: '/quizzes'
      fullPath: '/student/quizzes'
      preLoaderRoute: typeof StudentQuizzesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/leaderboard': {
      id: '/student/leaderboard'
      path: '/leaderboard'
      fullPath: '/student/leaderboard'
      preLoaderRoute: typeof StudentLeaderboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/achievements': {
      id: '/student/achievements'
      path: '/achievements'
      fullPath: '/student/achievements'
      preLoaderRoute: typeof StudentAchievementsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/parent/schedule': {
      id: '/parent/schedule'
      path: '/schedule'
      fullPath: '/parent/schedule'
      preLoaderRoute: typeof ParentScheduleRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/messages': {
      id: '/parent/messages'
      path: '/messages'
      fullPath: '/parent/messages'
      preLoaderRoute: typeof ParentMessagesRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/children': {
      id: '/parent/children'
      path: '/children'
      fullPath: '/parent/children'
      preLoaderRoute: typeof ParentChildrenRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/billing': {
      id: '/parent/billing'
      path: '/billing'
      fullPath: '/parent/billing'
      preLoaderRoute: typeof ParentBillingRouteImport
      parentRoute: typeof ParentRoute
    }
    '/assistant/reports': {
      id: '/assistant/reports'
      path: '/reports'
      fullPath: '/assistant/reports'
      preLoaderRoute: typeof AssistantReportsRouteImport
      parentRoute: typeof AssistantRoute
    }
    '/assistant/grading': {
      id: '/assistant/grading'
      path: '/grading'
      fullPath: '/assistant/grading'
      preLoaderRoute: typeof AssistantGradingRouteImport
      parentRoute: typeof AssistantRoute
    }
    '/assistant/discussions': {
      id: '/assistant/discussions'
      path: '/discussions'
      fullPath: '/assistant/discussions'
      preLoaderRoute: typeof AssistantDiscussionsRouteImport
      parentRoute: typeof AssistantRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBillingRoute: typeof AdminBillingRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminStaffRoute: typeof AdminStaffRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBillingRoute: AdminBillingRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminStaffRoute: AdminStaffRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AssistantRouteChildren {
  AssistantDiscussionsRoute: typeof AssistantDiscussionsRoute
  AssistantGradingRoute: typeof AssistantGradingRoute
  AssistantReportsRoute: typeof AssistantReportsRoute
}

const AssistantRouteChildren: AssistantRouteChildren = {
  AssistantDiscussionsRoute: AssistantDiscussionsRoute,
  AssistantGradingRoute: AssistantGradingRoute,
  AssistantReportsRoute: AssistantReportsRoute,
}

const AssistantRouteWithChildren = AssistantRoute._addFileChildren(
  AssistantRouteChildren,
)

interface ParentRouteChildren {
  ParentBillingRoute: typeof ParentBillingRoute
  ParentChildrenRoute: typeof ParentChildrenRoute
  ParentMessagesRoute: typeof ParentMessagesRoute
  ParentScheduleRoute: typeof ParentScheduleRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentBillingRoute: ParentBillingRoute,
  ParentChildrenRoute: ParentChildrenRoute,
  ParentMessagesRoute: ParentMessagesRoute,
  ParentScheduleRoute: ParentScheduleRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

interface StudentRouteChildren {
  StudentAchievementsRoute: typeof StudentAchievementsRoute
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentLeaderboardRoute: typeof StudentLeaderboardRoute
  StudentQuizzesRoute: typeof StudentQuizzesRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAchievementsRoute: StudentAchievementsRoute,
  StudentCoursesRoute: StudentCoursesRoute,
  StudentLeaderboardRoute: StudentLeaderboardRoute,
  StudentQuizzesRoute: StudentQuizzesRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AssistantRoute: AssistantRouteWithChildren,
  ClassesRoute: ClassesRoute,
  MarketplaceRoute: MarketplaceRoute,
  OnboardingRoute: OnboardingRoute,
  OwnerRoute: OwnerRoute,
  ParentRoute: ParentRouteWithChildren,
  QuizBankRoute: QuizBankRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
